/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BeritaRouteImport } from './routes/berita'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HasilRouteImport } from './routes/hasil'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LupaPasswordRouteImport } from './routes/lupa-password'
import { Route as PetunjukRouteImport } from './routes/petunjuk'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as SilabusRouteImport } from './routes/silabus'
import { Route as UjianRouteImport } from './routes/ujian'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PengawasIndexRouteImport } from './routes/pengawas.index'
import { Route as PengawasLogRouteImport } from './routes/pengawas.log'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaRoute = BeritaRouteImport.update({
  id: '/berita',
  path: '/berita',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HasilRoute = HasilRouteImport.update({
  id: '/hasil',
  path: '/hasil',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LupaPasswordRoute = LupaPasswordRouteImport.update({
  id: '/lupa-password',
  path: '/lupa-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PetunjukRoute = PetunjukRouteImport.update({
  id: '/petunjuk',
  path: '/petunjuk',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const SilabusRoute = SilabusRouteImport.update({
  id: '/silabus',
  path: '/silabus',
  getParentRoute: () => rootRouteImport,
} as any)
const UjianRoute = UjianRouteImport.update({
  id: '/ujian',
  path: '/ujian',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PengawasIndexRoute = PengawasIndexRouteImport.update({
  id: '/pengawas/',
  path: '/pengawas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PengawasLogRoute = PengawasLogRouteImport.update({
  id: '/pengawas/log',
  path: '/pengawas/log',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/berita': typeof BeritaRoute
  '/dashboard': typeof DashboardRoute
  '/hasil': typeof HasilRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/petunjuk': typeof PetunjukRoute
  '/profil': typeof ProfilRoute
  '/silabus': typeof SilabusRoute
  '/ujian': typeof UjianRoute
  '/pengawas/log': typeof PengawasLogRoute
  '/admin/': typeof AdminIndexRoute
  '/pengawas/': typeof PengawasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/berita': typeof BeritaRoute
  '/dashboard': typeof DashboardRoute
  '/hasil': typeof HasilRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/petunjuk': typeof PetunjukRoute
  '/profil': typeof ProfilRoute
  '/silabus': typeof SilabusRoute
  '/ujian': typeof UjianRoute
  '/pengawas/log': typeof PengawasLogRoute
  '/admin': typeof AdminIndexRoute
  '/pengawas': typeof PengawasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/berita': typeof BeritaRoute
  '/dashboard': typeof DashboardRoute
  '/hasil': typeof HasilRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/petunjuk': typeof PetunjukRoute
  '/profil': typeof ProfilRoute
  '/silabus': typeof SilabusRoute
  '/ujian': typeof UjianRoute
  '/pengawas/log': typeof PengawasLogRoute
  '/admin/': typeof AdminIndexRoute
  '/pengawas/': typeof PengawasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/berita'
    | '/dashboard'
    | '/hasil'
    | '/lobby'
    | '/login'
    | '/lupa-password'
    | '/petunjuk'
    | '/profil'
    | '/silabus'
    | '/ujian'
    | '/pengawas/log'
    | '/admin/'
    | '/pengawas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/berita'
    | '/dashboard'
    | '/hasil'
    | '/lobby'
    | '/login'
    | '/lupa-password'
    | '/petunjuk'
    | '/profil'
    | '/silabus'
    | '/ujian'
    | '/pengawas/log'
    | '/admin'
    | '/pengawas'
  id:
    | '__root__'
    | '/'
    | '/berita'
    | '/dashboard'
    | '/hasil'
    | '/lobby'
    | '/login'
    | '/lupa-password'
    | '/petunjuk'
    | '/profil'
    | '/silabus'
    | '/ujian'
    | '/pengawas/log'
    | '/admin/'
    | '/pengawas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeritaRoute: typeof BeritaRoute
  DashboardRoute: typeof DashboardRoute
  HasilRoute: typeof HasilRoute
  LobbyRoute: typeof LobbyRoute
  LoginRoute: typeof LoginRoute
  LupaPasswordRoute: typeof LupaPasswordRoute
  PetunjukRoute: typeof PetunjukRoute
  ProfilRoute: typeof ProfilRoute
  SilabusRoute: typeof SilabusRoute
  UjianRoute: typeof UjianRoute
  PengawasLogRoute: typeof PengawasLogRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PengawasIndexRoute: typeof PengawasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita': {
      id: '/berita'
      path: '/berita'
      fullPath: '/berita'
      preLoaderRoute: typeof BeritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hasil': {
      id: '/hasil'
      path: '/hasil'
      fullPath: '/hasil'
      preLoaderRoute: typeof HasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lupa-password': {
      id: '/lupa-password'
      path: '/lupa-password'
      fullPath: '/lupa-password'
      preLoaderRoute: typeof LupaPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petunjuk': {
      id: '/petunjuk'
      path: '/petunjuk'
      fullPath: '/petunjuk'
      preLoaderRoute: typeof PetunjukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/silabus': {
      id: '/silabus'
      path: '/silabus'
      fullPath: '/silabus'
      preLoaderRoute: typeof SilabusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ujian': {
      id: '/ujian'
      path: '/ujian'
      fullPath: '/ujian'
      preLoaderRoute: typeof UjianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengawas/': {
      id: '/pengawas/'
      path: '/pengawas'
      fullPath: '/pengawas/'
      preLoaderRoute: typeof PengawasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengawas/log': {
      id: '/pengawas/log'
      path: '/pengawas/log'
      fullPath: '/pengawas/log'
      preLoaderRoute: typeof PengawasLogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeritaRoute: BeritaRoute,
  DashboardRoute: DashboardRoute,
  HasilRoute: HasilRoute,
  LobbyRoute: LobbyRoute,
  LoginRoute: LoginRoute,
  LupaPasswordRoute: LupaPasswordRoute,
  PetunjukRoute: PetunjukRoute,
  ProfilRoute: ProfilRoute,
  SilabusRoute: SilabusRoute,
  UjianRoute: UjianRoute,
  PengawasLogRoute: PengawasLogRoute,
  AdminIndexRoute: AdminIndexRoute,
  PengawasIndexRoute: PengawasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
